Repository peer-42seoul/Peer-Frontend, pull requests merged in 2023-12, with the labels that each got.

#388 [H-SC] 쇼케이스
  package-lock.json
  package.json
  src/app/panel/MainLayout.tsx
  src/app/panel/NavBar.tsx
  src/app/showcase/layout.tsx
  src/app/showcase/page.tsx
  src/app/showcase/panel/PhoneFrame.tsx
  src/app/showcase/panel/ShowcaseCard.tsx
  src/app/showcase/panel/ShowcaseHeader.tsx
Labels: new feature

#391 Mui TextField 스타일 오버라이드 작업
  src/app/find-account/panel/SendCodeForm.tsx
  src/app/find-account/panel/SendEmailForm.tsx
  src/app/login/page.tsx
  src/app/panel/MuiThemeProvider.tsx
  src/app/signup/page.tsx
  src/app/signup/panel/CodeField.tsx
  src/app/signup/panel/CodeTimer.tsx
  src/app/signup/panel/EmailField.tsx
  src/app/signup/panel/NameField.tsx
  src/app/signup/panel/NickNameField.tsx
  src/app/signup/panel/PasswordField.tsx
Labels: Design

#403 [C-MYPAGE] 개별 쪽지 페이지 PC 뷰 디자인, CuAvatar 추가
  src/app/my-page/message/[id]/page.style.ts
  src/app/my-page/message/[id]/page.tsx
  src/app/my-page/message/[id]/panel/MessageContainer.style.ts
  src/app/my-page/message/[id]/panel/MessageContainer.tsx
  src/app/my-page/message/[id]/panel/MessageForm.style.ts
  src/app/my-page/message/[id]/panel/MessageForm.tsx
  src/app/my-page/message/[id]/panel/MessageHeader.style.ts
  src/app/my-page/message/[id]/panel/MessageHeader.tsx
  src/app/my-page/message/[id]/panel/MessageItem.style.ts
  src/app/my-page/message/[id]/panel/MessageItem.tsx
  src/app/my-page/message/[id]/panel/MessageStack.tsx
  src/components/CuAvatar.style.ts
  src/components/CuAvatar.tsx
  src/hook/useInfiniteScroll.tsx
  src/icons/SendIcon.tsx
Labels: Design

#396 [H-HITCH] 히치하이킹 데모
  package-lock.json
  package.json
  src/app/hitchhiking/page.tsx
  src/app/hitchhiking/panel/CardContainer.tsx
  src/app/hitchhiking/panel/HitchhikingCard.tsx
  src/app/panel/MainLayout.tsx
  src/components/PostCard.tsx
  src/types/IPostCard.ts
Labels: new feature

#409 [C-MYPAGE] 마이페이지 개인정보 페이지 디자인 적용
  src/app/my-page/privacy/page.tsx
  src/app/my-page/privacy/panel/UserInfoEdit.tsx
  src/app/my-page/profile/panel/MyInfoCard.tsx
  src/app/my-page/profile/panel/ProfileCard.tsx
Labels: Design

#414 [PUBLIC] CuModal, CuTextModal 공통 컴포넌트 추가
  src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
  src/app/my-page/interests/page.tsx
  src/app/my-page/message/[id]/panel/MessageForm.tsx
  src/app/my-page/message/[id]/panel/MessageFormModal.tsx
  src/app/my-page/message/panel/NewMessageForm.tsx
  src/app/my-page/message/panel/NewMessageModal.tsx
  src/app/my-page/privacy/panel/UserWithdrawalModal.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/profile/panel/ProfileBioEditor.tsx
  src/app/my-page/profile/panel/ProfileLinkEditor.tsx
  src/app/my-page/profile/panel/SettingContainer.tsx
  src/app/panel/layout-panel/NavBar.tsx
  src/app/panel/main-page/SearchButton.tsx
  src/app/recruit/[id]/panel/ApplyButton.tsx
  src/app/recruit/[id]/panel/LinkButton.tsx
  src/app/recruit/[id]/panel/form/ConfirmModal.tsx
  src/app/teams/[id]/panel/widgets/WidgetsRender.tsx
  src/app/teams/[id]/setting/panel/SetupTeam.tsx
  src/components/CuButton.tsx
  src/components/CuModal.style.ts
  src/components/CuModal.tsx
  src/components/CuTextModal.tsx
  src/components/CuWarning.tsx
  src/icons/ChevronLeft.tsx
  src/icons/CloseIcon.tsx
Labels: Design

#435 [C-MYPAGE] 쪽지 목록 페이지 (PC뷰) 디자인, BackgroundBox 컴포넌트 추가, 쪽지 목록 관리 데이터 변경
  src/app/my-page/message/@detail/panel/PcHeader.tsx
  src/app/my-page/message/@list/page.style.ts
  src/app/my-page/message/@list/page.tsx
  src/app/my-page/message/@list/panel/MessageBar.style.ts
  src/app/my-page/message/@list/panel/MessageBar.tsx
  src/app/my-page/message/@list/panel/MessageContainer.style.tsx
  src/app/my-page/message/@list/panel/MessageContainer.tsx
  src/app/my-page/message/@list/panel/MessageItemBase.style.ts
  src/app/my-page/message/@list/panel/MessageItemBase.tsx
  src/app/my-page/message/@list/panel/MessageList.style.ts
  src/app/my-page/message/@list/panel/MessageList.tsx
  src/app/my-page/message/@list/panel/NewMessageForm.style.ts
  src/app/my-page/message/@list/panel/NewMessageForm.tsx
  src/app/my-page/message/@list/panel/NewMessageModal.style.ts
  src/app/my-page/message/@list/panel/NewMessageModal.tsx
  src/app/my-page/message/@list/panel/PCMessageItem.tsx
  src/app/my-page/message/@list/panel/PCMessageListItem.style.ts
  src/app/my-page/message/@list/panel/TargetList.style.ts
  src/app/my-page/message/@list/panel/TargetList.tsx
  src/components/BackgroundBox.style.ts
  src/components/BackgroundBox.tsx
  src/components/BoxBase.tsx
  src/components/CuModal.style.ts
  src/components/CuModal.tsx
  src/icons/PlusIcon.tsx
  src/icons/SearchIcon.tsx
  src/icons/index.ts
Labels: bug, Design

#441 [DESIGN] 모집글 버튼 z-index 조정
  src/app/panel/layout-panel/NavBar.tsx
  src/app/recruit/[id]/panel/ApplyButton.tsx
  src/app/recruit/[id]/panel/LinkButton.style.ts
  src/app/recruit/[id]/panel/LinkButton.tsx
Labels: bug, Design

#444 [H-HITCH] 히치하이킹 카드 배경 적용
  src/app/hitchhiking/panel/CardContainer.tsx
Labels: enhancement

#437 [C-MYPAGE] 쪽지 목록 페이지 (모바일 뷰) 디자인, 마이페이지 레이아웃 수정
  src/app/my-page/layout.style.ts
  src/app/my-page/layout.tsx
  src/app/my-page/message/@list/page.style.ts
  src/app/my-page/message/@list/page.tsx
  src/app/my-page/message/@list/panel/MessageBar.style.ts
  src/app/my-page/message/@list/panel/MessageBar.tsx
  src/app/my-page/message/@list/panel/MessageContainer.tsx
  src/app/my-page/message/@list/panel/MessageItemBase.style.ts
  src/app/my-page/message/@list/panel/MessageItemBase.tsx
  src/app/my-page/message/@list/panel/MobileMessageItem.style.ts
  src/app/my-page/message/@list/panel/MobileMessageItem.tsx
  src/app/my-page/message/@list/panel/NewMessageModal.style.ts
  src/app/my-page/message/@list/panel/NewMessageModal.tsx
  src/app/my-page/message/@list/panel/PCMessageListItem.style.ts
  src/app/my-page/page.tsx
  src/app/my-page/panel/NavBar.style.tsx
  src/app/my-page/panel/NavBar.tsx
  src/icons/FilledMessageIcon.tsx
  src/icons/MyPageHeartIcon.tsx
  src/icons/SettingIcon.tsx
  src/icons/SilhouetteIcon.tsx
  src/icons/WhaleIcon.tsx
  src/icons/index.ts
Labels: Design
