Repository peer-42seoul/Peer-Frontend, pull requests merged in 2023-11, with the labels that each got.

#153 [I-TM] 팀 설정 페이지에서 설문 답안 폼 변경
  public/images/teamLogo.png
  src/api/location.tsx
  src/app/panel/FormCheckbox.tsx
  src/app/recruitment/[id]/panel/CheckQuestionForm.tsx
  src/app/recruitment/[id]/panel/CloseQuestionForm.tsx
  src/app/recruitment/[id]/panel/RatioQuestionForm.tsx
  src/app/recruitment/[id]/panel/RecruitFormModal.tsx
  src/app/team-list/page.tsx
  src/app/team-list/panel/TeamsList.tsx
  src/app/teams/@setting/[id]/page.tsx
  src/app/teams/@setting/[id]/panel/ApplicantList.tsx
  src/app/teams/@setting/[id]/panel/RecuitFormAnswer.tsx
  src/app/teams/@setting/[id]/panel/SetupMember.tsx
  src/app/teams/@setting/[id]/panel/SetupSelect.tsx
  src/app/teams/@setting/[id]/panel/SetupTeam.tsx
Labels: enhancement

#181 [D-TP-01~03, 21~24, 39, 42, 43] 팀 페이지 기존 와이어프레임에 맞게 기능 삭제 / 추가
  src/app/teams/@main/[id]/panel/TeamInfoComponent.tsx
  src/app/teams/@main/[id]/panel/TeamInfoContainer.tsx
  src/app/teams/@main/[id]/panel/TeamMemberModal.tsx
  src/types/ITeamInfo.ts
Labels: link API

#186 [C-SRC] 지난 검색어 클릭 액션 추가
  .gitignore
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
Labels: bug

#192 [B-INFO] 회원가입 인증코드 에러 수정
  src/app/signup/page.tsx
  src/app/signup/panel/CodeField.tsx
Labels: bug

#182 [C-MYPAGE] 관심 리스트 데이터 섞임 문제 해결
  src/app/my-page/interests/page.tsx
Labels: bug

#190 [C-MAIN][C-TB] 메인페이지 api 변경, 세부옵션 오류 수정, 타입 수정, 관심글 클릭시 로그인 확인, 네비게이션 수정 등
  src/api/location.tsx
  src/app/my-page/interests/page.tsx
  src/app/page.tsx
  src/app/panel/EditButton.tsx
  src/app/panel/FormCheckbox.tsx
  src/app/panel/MainCard.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/MainProfile.tsx
  src/app/panel/MainShowcase.tsx
  src/app/panel/NavBar.tsx
  src/app/panel/Options.tsx
  src/app/panel/SearchOption.tsx
  src/app/panel/SelectSort.tsx
  src/app/panel/SelectType.tsx
  src/app/recruitment/[id]/page.tsx
  src/app/teams/@setting/[id]/panel/SetupSelect.tsx
  src/types/IPostDetail.ts
Labels: bug, link API

#185 [C-MYPAGE] 키워드 알림 설정 중복 키워드 에러 핸들링 추가
  src/app/my-page/homepage-setting/page.tsx
  src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
  src/app/my-page/interests/page.tsx
  src/app/my-page/panel/SubNavBar.tsx
Labels: enhancement

#215 CI / CD 환경 구축
  .github/workflows/main.yml
  Dockerfile
  next.config.js
Labels: environment

#220 [C-MYPAGE] swr이 무한히 요청 보내던 현상 제거
  src/app/layout.tsx
  src/app/my-page/interests/page.tsx
  src/app/my-page/profile/page.tsx
  src/app/panel/CuSWRConfig.tsx
Labels: bug

#203 [C-MYPAGE] 쪽지 api 연결, 리팩토링, 기능 추가
  src/app/my-page/message/MessageList.tsx
  src/app/my-page/message/MessageWritingForm.tsx
  src/app/my-page/message/[id]/page.tsx
  src/app/my-page/message/page.tsx
  src/app/my-page/message/panel/MessageContainer.tsx
  src/app/my-page/message/panel/MessageList.tsx
  src/app/my-page/message/panel/MessageWritingFormModal.tsx
  src/hook/useInfiniteScroll.tsx
Labels: link API

#225 [C-SRC] 지난 검색어 기능 수리
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
Labels: bug

#226 [C-MYPAGE] SubNavBar 포커싱 오류 처리, 키워드 세팅 전체 삭제 api 처리 로직 변경
  src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
  src/app/my-page/panel/SubNavBar.tsx
Labels: bug

#230 [C-MYPAGE] 쪽지 api 무한요청 버그 수정 및 쪽지 관련 버그 일부 수정
  src/app/my-page/message/page.tsx
  src/app/my-page/message/panel/MessageContainer.tsx
  src/app/my-page/message/panel/MessageWritingFormModal.tsx
  src/states/useMessageDataState.tsx
  src/states/useMessageStore.tsx
Labels: bug

#233 [C-MYPAGE] 프로필 소개 수정 시 전송 본문 타입 변경
  src/app/my-page/profile/panel/ProfileBioEditor.tsx
Labels: enhancement

#245 [C-SIGN] find-account 페이지의 api 연동 오류 수정 + interceptor reissue 오류 수정
  src/api/config.ts
  src/app/find-account/panel/SendCodeForm.tsx
  src/app/find-account/panel/SendEmailForm.tsx
Labels: link API

#249 [C-MAIN][J-TB] 메인페이지, 모집글 뷰페이지의 API 연동에 따른 변수수정 + 세부옵션 수정
  src/app/my-page/interests/page.tsx
  src/app/page.tsx
  src/app/panel/MainCard.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/MainProfile.tsx
  src/app/panel/Options.tsx
  src/app/recruitment/[id]/page.tsx
  src/app/recruitment/[id]/panel/RecruitFormModal.tsx
  src/app/recruitment/[id]/panel/RecruitFormText.tsx
  src/app/teams/@setting/[id]/panel/SetupSelect.tsx
  src/types/IPagination.ts
  src/types/IPostDetail.ts
Labels: bug, link API

#248 [C-MYPAGE-37,38] 관심있는 프로젝트 페이지 데이터가 없을 시, 타입 토글이나 탭도 나타나지 않는 현상 수정
  src/app/my-page/interests/page.tsx
  src/app/my-page/interests/panel/InterestsContents.tsx
Labels: bug

#299 [FIX] 로그인 상태에서 회원가입 접근 막기 및 회원 탈퇴 후 Zustand Login 상태 초기화
  src/app/my-page/privacy/panel/UserWithdrawalModal.tsx
  src/app/privacy/page.tsx
  src/app/signup/page.tsx
Labels: bug

#323 [C-SIGN-01] 로그인 페이지 와이어프레임 수정
  .gitignore
  public/icons/g-logo.png
  src/app/find-account/page.tsx
  src/app/find-account/panel/FindComplete.tsx
  src/app/find-account/panel/SendCodeForm.tsx
  src/app/find-account/panel/SendEmailForm.tsx
  src/app/login/page.tsx
  src/app/login/panel/OauthLoginBox.tsx
  src/app/panel/MainPage.tsx
  src/app/privacy/page.tsx
  src/app/signup/page.tsx
  src/app/signup/panel/CodeField.tsx
  src/app/signup/panel/EmailField.tsx
  src/app/signup/panel/NickNameField.tsx
  src/app/signup/panel/PasswordField.tsx
  src/components/BoxBase.tsx
Labels: Design

#345 [PUBLIC] 디자인 색 커스텀 추가
  src/app/panel/MainLayout.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/MuiThemeProvider.tsx
  src/app/panel/NavBar.tsx
  src/states/useDarkMode.ts
Labels: Design

#365 [K-PWA] I-TM 설정 수정 및 PWA 설치 배너 수정, 검색창 오류 수정
  package-lock.json
  package.json
  src/app/login/oauth/page.tsx
  src/app/page.tsx
  src/app/panel/PushAlertBanner.tsx
  src/app/panel/PwaInstallBanner.tsx
  src/app/panel/SearchButton.tsx
  src/app/search/panel/SearchBody.tsx
  src/app/teams/@setting/[id]/page.tsx
  src/app/teams/@setting/[id]/panel/SetupTeam.tsx
  src/components/CuModal.tsx
  src/states/useAuthStore.tsx
Labels: bug

#371 [D-TP] 팀 공지사항 게시판 나머지 기능 구현
  src/app/teams/@notice/[id]/notice-edit/[postId]/page.tsx
  src/app/teams/@notice/[id]/notice-edit/page.tsx
  src/app/teams/@notice/[id]/notice-edit/panel/NoticeEditButton.tsx
  src/app/teams/@notice/[id]/notice-edit/panel/NoticeEditContainer.tsx
  src/app/teams/@notice/[id]/notice-edit/panel/NoticeEditForm.tsx
  src/app/teams/@notice/[id]/notice/[postId]/page.tsx
  src/app/teams/@notice/[id]/notice/[postId]/panel/CommentList.tsx
  src/app/teams/@notice/[id]/page.tsx
  src/app/teams/@notice/[id]/panel/NoticeList.tsx
  src/components/CuButton.tsx
Labels: new feature

#370 [C-SIGN] 로그인, 회원가입, 비밀번호 찾기 페이지 디자인 적용
  src/api/config.ts
  src/app/find-account/page.tsx
  src/app/find-account/panel/FindComplete.tsx
  src/app/find-account/panel/SendCodeForm.tsx
  src/app/find-account/panel/SendEmailForm.tsx
  src/app/login/page.tsx
  src/app/login/panel/OauthLoginBox.tsx
  src/app/privacy/page.tsx
  src/app/signup/page.tsx
  src/app/signup/panel/CodeField.tsx
  src/app/signup/panel/EmailField.tsx
  src/app/signup/panel/PasswordField.tsx
  src/components/BoxBase.tsx
  src/components/EyeIcon.tsx
Labels: Design

#392 [C-MYPAGE] 쪽지 보내기 기능 누락 수정
  src/app/my-page/message/[id]/panel/MessageForm.tsx
Labels: bug
