Repository peer-42seoul/Peer-Frontend, pull requests merged in 2023-09, with the labels that each got.

#21 Fix/eslint options
  peer_web_frontend/.eslintrc.json
Labels: bug

#25 [C-SIGN-01] 로그인 입력창 작성
  peer_web_frontend/src/app/login/page.tsx
Labels: new feature

#26 [C-MYPAGE] 쪽지
  peer_web_frontend/src/components/MessageContent.tsx
  peer_web_frontend/src/components/MessageList.server.tsx
Labels: new feature

#32 Chore: add zustand store folder
  peer_web_frontend/src/app/login/page.tsx
  peer_web_frontend/src/states/useAuthStore.tsx
  peer_web_frontend/tsconfig.json
Labels: new feature

#48 Feat: Add mock server function
  peer_web_frontend/mock/.gitignore
  peer_web_frontend/mock/readme.md
  peer_web_frontend/mock/start.sh
Labels: new feature

#56 [C-MYPAGE] 쪽지
  peer_web_frontend/mock/routes.json
  peer_web_frontend/src/app/profile/message/MessageList.tsx
  peer_web_frontend/src/app/profile/message/[id]/page.tsx
  peer_web_frontend/src/app/profile/message/page.tsx
  peer_web_frontend/src/app/profile/message/view/page.tsx
  peer_web_frontend/src/app/profile/message/write/MessageForm.tsx
  peer_web_frontend/src/app/profile/message/write/page.tsx
  peer_web_frontend/src/components/MessageList.tsx
  peer_web_frontend/src/components/MessageNavigator.tsx
  peer_web_frontend/src/components/ModalContainer.tsx
  peer_web_frontend/src/states/useMessageStore.tsx
Labels: new feature

#67 [C-SIGN-03] 비밀번호 찾기 페이지 수정
  peer_web_frontend/src/app/find-account/page.tsx
  peer_web_frontend/src/app/find-account/panel/SendCodeForm.tsx
  peer_web_frontend/src/app/find-account/panel/SendEmailForm.tsx
Labels: enhancement

#70 [C-MYPAGE] 쪽지 팀 리스트 기능
  package-lock.json
  peer_web_frontend/next.config.js
  peer_web_frontend/src/app/profile/message/MessageList.tsx
  peer_web_frontend/src/app/profile/message/[id]/page.tsx
  peer_web_frontend/src/app/profile/message/page.tsx
  peer_web_frontend/src/app/profile/message/view/page.tsx
  peer_web_frontend/src/app/profile/message/write/MessageForm.tsx
  peer_web_frontend/src/app/profile/message/write/page.tsx
  peer_web_frontend/src/types/IMessageInformation.ts
Labels: enhancement

#62 [C-MYPAGE] 프로필 수정 버튼 동작 구현
  peer_web_frontend/mock/start.sh
  peer_web_frontend/src/app/profile/MyPage/page.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/ProfileCard.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinksSection.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/ProfileSection.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/ProfileSectionEditLink.tsx
  peer_web_frontend/src/app/profile/MyPage/panel/SettingContainer.tsx
  peer_web_frontend/src/types/IUserProfile.ts
Labels: new feature
