Repository peer-42seoul/Peer-Frontend, pull requests merged in 2023-10, with the labels that each got.

#94 [C-MYPAGE-49~54, I-TM] 나의 팀 페이지 and 설정 페이지
  peer_web_frontend/src/app/find-account/panel/SendCodeForm.tsx
  peer_web_frontend/src/app/panel/NavBar.tsx
  peer_web_frontend/src/app/teams/layout.tsx
  peer_web_frontend/src/app/teams/page.tsx
  peer_web_frontend/src/app/teams/panel/TeamsList.tsx
  peer_web_frontend/src/app/teams/setup/[id]/page.tsx
  peer_web_frontend/src/app/teams/setup/panel/SetupMember.tsx
  peer_web_frontend/src/app/teams/setup/panel/SetupTeam.tsx
  peer_web_frontend/src/app/teams/setup/panel/Sidebar.tsx
  peer_web_frontend/src/hook/useMedia.tsx
  peer_web_frontend/src/states/useShowTeams.tsx
Labels: new feature

#97 [C-SIGN-01, 04] 소셜 로그인 링크 추가, PC용 와이어프레임 작성
  peer_web_frontend/src/app/api/auth/[...nextauth]/route.ts
  peer_web_frontend/src/app/api/auth/signup/page.tsx
  peer_web_frontend/src/app/login/page.tsx
Labels: enhancement, Design

#98 [J-TB-1 ~ 28] 모집글쓰기 페이지, 3개로 나뉘어있던 BasicSelect를 하나의 파일로 통합
  peer_web_frontend/src/app/create-team/BasicSelectArea.tsx
  peer_web_frontend/src/app/create-team/BasicSelectMonth.tsx
  peer_web_frontend/src/app/create-team/BasicSelectTeamSize.tsx
  peer_web_frontend/src/app/create-team/page.tsx
  peer_web_frontend/src/app/recruitment/page.tsx
  peer_web_frontend/src/app/recruitment/panel/BasicSelect.tsx
  peer_web_frontend/src/app/recruitment/panel/CommunicationToolLink.tsx
  peer_web_frontend/src/app/recruitment/panel/SetTeamRole.tsx
  peer_web_frontend/src/app/recruitment/panel/TagAutoComplete.tsx
  peer_web_frontend/src/app/recruitment/panel/TeamTag.tsx
  peer_web_frontend/src/app/recruitment/panel/WorkWeekend.tsx
  peer_web_frontend/src/app/recruitment/panel/radioGroup.tsx
Labels: enhancement

#131 [C-MYPAGE] 프로필 변경 api 연결
  peer_web_frontend/src/app/my-page/profile/panel/ProfileBioEditor.tsx
  peer_web_frontend/src/app/my-page/profile/panel/ProfileLinkEditor.tsx
  peer_web_frontend/src/app/my-page/profile/panel/SettingContainer.tsx
  peer_web_frontend/src/components/CuButton.tsx
Labels: link API

#151 [C-SRC] 지난 검색어 기능 구현
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
Labels: enhancement

#157 [C-SIGN] API수정 및 useAuthStore 수정
  src/api/config.ts
  src/states/useAuthStore.tsx
Labels: link API

#169 테스트를 위한 타입 오류 수정
  src/app/my-page/message/MessageForm.tsx
  src/app/my-page/message/MessageList.tsx
  src/app/my-page/message/MessageWritingForm.tsx
  src/app/my-page/message/[id]/page.tsx
  src/app/my-page/message/view/page.tsx
  src/app/panel/SearchOption.tsx
  src/app/team-list/page.tsx
Labels: wontfix

#167 [C-MYPAGE] 프로필, 관심 리스트, 홈페이지 설정(알림키워드) api 연결
  src/api/fetchers.ts
  src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
  src/app/my-page/interests/page.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/profile/panel/ProfileBioEditor.tsx
  src/app/my-page/profile/panel/ProfileCard.tsx
  src/app/my-page/profile/panel/ProfileLinkEditor.tsx
  src/app/my-page/profile/panel/ProfileSection.tsx
  src/app/my-page/profile/panel/SettingContainer.tsx
  src/app/panel/MainCarousel.tsx
Labels: link API
