Repository peer-42seoul/Peer-Frontend, pull requests merged in 2024-01, with the labels that each got.

#449 [C-MAIN][J-TB] 메인/모집글 디자인 추가
  src/app/panel/MainPage.tsx
  src/app/panel/layout-panel/NavBar.tsx
  src/app/panel/main-page/FormCheckbox.tsx
  src/app/panel/main-page/MainBanner.tsx
  src/app/panel/main-page/MainCard.tsx
  src/app/panel/main-page/MainCarousel.tsx
  src/app/panel/main-page/MainProfile.tsx
  src/app/panel/main-page/Options.tsx
  src/app/panel/main-page/SearchOption.tsx
  src/app/panel/main-page/SelectType.tsx
  src/app/recruit/[id]/page.tsx
  src/app/recruit/[id]/panel/ApplyButton.tsx
  src/app/recruit/[id]/panel/LinkButton.tsx
  src/app/recruit/[id]/panel/RecruitContentText.tsx
  src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
  src/app/recruit/[id]/panel/SirenIcon.tsx
  src/app/recruit/[id]/panel/form/CloseQuestionForm.tsx
  src/app/recruit/[id]/panel/form/RecruitFormModal.tsx
  src/app/teams/[id]/setting/panel/SetupSelect.tsx
  src/components/FavoriteButton.tsx
  src/components/TagAutoComplete.tsx
  src/components/TagChip.tsx
  src/types/IPostDetail.ts
Labels: Design

#450 [D-TP] 캘린더 PC 위젯
  src/app/teams/[id]/panel/CalendarComponent.tsx
  src/app/teams/[id]/panel/CalendarLarge.tsx
  src/app/teams/[id]/panel/CalendarLargeTest.tsx
  src/app/teams/[id]/panel/CalendarMini.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/Calendar.scss
  src/app/teams/[id]/panel/widgets/CalenderWidget/Calendar.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarComponent.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarLarge.scss
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarLarge.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarMini.scss
  src/app/teams/[id]/panel/widgets/CalenderWidget/PreviewModal.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/_theme.scss
  src/app/teams/[id]/panel/widgets/CalenderWidget/index.style.ts
  src/app/teams/[id]/panel/widgets/CalenderWidget/index.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/utils.ts
  src/app/teams/[id]/panel/widgets/TmpCalenderWidget.tsx
  src/app/teams/[id]/panel/widgets/WidgetCard.style.ts
  src/app/teams/[id]/panel/widgets/WidgetCard.tsx
  src/app/teams/[id]/panel/widgets/WidgetList.tsx
  src/app/teams/[id]/panel/widgets/WidgetsRender.tsx
  src/app/teams/[id]/style/CalendarLarge.scss
  src/app/teams/[id]/style/CalendarMini.scss
  src/types/WidgetDataTypes.ts
Labels: new feature, Design

#433 [D-FIN] ToastUIEditor 추가
  package-lock.json
  package.json
  src/app/team-list/layout.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/SetupMember.tsx
  src/app/teams/[id]/setting/panel/SetupProject.tsx
  src/app/teams/[id]/setting/panel/SetupStudy.tsx
  src/components/EditorWrapper.tsx
  src/components/ToastUIEditor.tsx
  src/components/complete/panel/BackgroundCard.tsx
  src/components/complete/panel/FiveStarReview.tsx
  src/components/complete/panel/TeamReviewAnswer.tsx
  src/components/complete/panel/TeamReviewCard.tsx
  src/components/complete/panel/TeamReviewQuestion.tsx
  src/components/complete/panel/types.ts
  src/types/editor.d.ts
  styles/global.css
Labels: new feature

#448 [D-TP] 팀페이지 DND 레이아웃 오류 및 배치 수정, 툴박스 캐러셀로 변환
  .github/ISSUE_TEMPLATE/기능-구현-전-작성-템플릿.md
  .github/ISSUE_TEMPLATE/버그-리포트-템플릿.md
  README.md
  package-lock.json
  package.json
  src/app/report/page.tsx
  src/app/report/panel/ReportTypeSelect.tsx
  src/app/teams/[id]/layout.tsx
  src/app/teams/[id]/page.tsx
  src/app/teams/[id]/panel/TeamDnD.tsx
  src/app/teams/[id]/panel/TeamSidebar.tsx
  src/app/teams/[id]/panel/widgets/TeamDnD.style.ts
  src/app/teams/[id]/panel/widgets/WidgetList.tsx
  src/app/teams/[id]/panel/widgets/WidgetsRender.tsx
  src/components/PostCard.tsx
  styles/global.css
  styles/reset.css
Labels: new feature

#446 [PUBLIC, C-MYPAGE] 라이트/다크모드 처리
  src/app/my-page/homepage-setting/panel/DisplaySetting.tsx
  src/app/my-page/message/@list/panel/MessageBar.tsx
  src/app/my-page/message/@list/panel/NewMessageModal.style.ts
  src/app/panel/MuiThemeProvider.tsx
  src/app/panel/layout-panel/AlertIcon.tsx
  src/app/panel/layout-panel/Header.style.ts
  src/app/panel/layout-panel/Header.tsx
  src/app/panel/layout-panel/NavBar.tsx
  src/app/panel/layout-panel/PeerLogo.tsx
  src/app/panel/main-page/SearchButton.tsx
  src/app/teams/[id]/notice/page.tsx
  src/components/CuToggle.tsx
  src/components/MessageNavigator.tsx
  src/constant/ColorTheme.ts
  src/icons/NotificationIcon.tsx
  src/icons/SearchIcon.tsx
  src/states/useDarkMode.ts
  src/types/DisplayTypes.ts
  styles/global.css
Labels: new feature, Design

#447 [PUBLIC] CuToast에 디자인 추가
  src/app/my-page/homepage-setting/page.tsx
  src/app/panel/MuiThemeProvider.tsx
  src/components/CuToast.style.ts
  src/components/CuToast.tsx
  src/constant/ColorTheme.ts
  src/icons/CloseIcon.tsx
Labels: Design

#443 [C-MYPAGE] 페이지 레이아웃 디자인 적용, 프로필 수정 디자인 적용
  src/app/my-page/homepage-setting/page.tsx
  src/app/my-page/interests/page.tsx
  src/app/my-page/panel/SubNavBar.tsx
  src/app/my-page/panel/my-page.style.ts
  src/app/my-page/privacy/page.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/profile/panel/MyInfoCard.tsx
  src/app/my-page/profile/panel/Profile.style.ts
  src/app/my-page/profile/panel/ProfileBioEditor.tsx
  src/app/my-page/profile/panel/ProfileCard.tsx
  src/app/my-page/profile/panel/ProfileLinkEditor.tsx
  src/app/my-page/profile/panel/ProfileLinksSection.tsx
  src/app/panel/MuiThemeProvider.tsx
  src/constant/ColorTheme.ts
  src/icons/TrashIcon.tsx
Labels: Design

#466 [D-TP] Toast UI Editor Viewer 추가, 팀 공지사항 게시판 라우팅 구조 변경
  src/app/teams/[id]/layout.tsx
  src/app/teams/[id]/notice/@detail/page.style.ts
  src/app/teams/[id]/notice/@detail/page.tsx
  src/app/teams/[id]/notice/@detail/panel/CommentList.tsx
  src/app/teams/[id]/notice/@edit/page.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditButton.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditContainer.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditForm.tsx
  src/app/teams/[id]/notice/@list/page.tsx
  src/app/teams/[id]/notice/@list/panel/NoticeList.tsx
  src/app/teams/[id]/notice/layout.tsx
  src/app/teams/[id]/notice/notice-edit/[postId]/page.tsx
  src/components/DynamicToastEditor.tsx
  src/components/DynamicToastViewer.tsx
  src/components/EditorWrapper.tsx
  src/components/ToastUIEditor.tsx
  src/components/ToastUIViewer.tsx
  src/states/useTeamPageState.ts
  src/types/ToastUI/editor.d.ts
  src/types/ToastUI/toastui-editor-viewer.d.ts
  src/types/editor.d.ts
Labels: enhancement

#468 [DESIGN] CuNavBar fullWidth Warning
  src/api/config.ts
  src/app/find-account/panel/SendCodeForm.tsx
  src/app/teams/[id]/layout.tsx
  src/components/CuNavBar.style.ts
  src/components/CuNavBar.tsx
Labels: bug

#472 [I-TM] 팀 설정 페이지의 팀 역할 변경 및 추가
  next.config.js
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
  src/app/teams/[id]/layout.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/AddNewJob.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/Icons.tsx
  src/app/teams/[id]/setting/panel/SetupInfo.tsx
  src/app/teams/[id]/setting/panel/SetupMember.tsx
  src/app/teams/[id]/setting/panel/SetupProject.tsx
  src/app/teams/[id]/setting/panel/SetupStudy.tsx
  src/app/teams/[id]/setting/panel/SetupTeam.tsx
  src/app/teams/[id]/setting/panel/TeamJobAdd.tsx
  src/app/teams/[id]/setting/panel/styles.ts
  src/app/teams/types/types.ts
  src/components/CuNavBar.tsx
Labels: environment

#471 [PUBLIC] CuToast 디자인 변경 및 message prop 타입 변경
  src/app/my-page/homepage-setting/page.tsx
  src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
  src/components/CuToast.tsx
Labels: enhancement, Design

#481 [J-TB] 모집글에 현재 지원상태 넣기, 모집글 버그 수정
  src/app/recruit/[id]/page.tsx
  src/app/recruit/[id]/panel/ApplyButton.tsx
  src/app/recruit/[id]/panel/ApplyDrawerButton.tsx
  src/app/recruit/[id]/panel/ApplyMenuButton.tsx
  src/app/recruit/[id]/panel/form/RecruitFormModal.tsx
  src/types/IPostDetail.ts
Labels: bug, enhancement

#473 [PUBLIC, C-MYPAGE] 프로필 페이지 내 작업물 ui 추가, TitleBox, PostCard 사용성 개선
  package-lock.json
  src/app/hitchhiking/panel/HitchhikingCard.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/profile/panel/MyPortfolio.tsx
  src/app/my-page/profile/panel/Profile.style.ts
  src/components/PostCard.style.ts
  src/components/PostCard.tsx
  src/components/TitleBox.style.ts
  src/components/TitleBox.tsx
  src/types/IPostCard.ts
Labels: enhancement, new feature

#482 [PUBLIC] MUI custom Breakpoints가 적용 안되는 문제 해결
  src/app/panel/MuiThemeProvider.tsx
  src/constant/ColorTheme.ts
Labels: bug

#483 [I-TM] 팀설정페이지에서 팀 역할 수정 기능 추가와 몇몇 리팩토링 진행
  next.config.js
  src/api/location.tsx
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/Icons.tsx
  src/app/teams/[id]/setting/panel/SetupInfo.tsx
  src/app/teams/[id]/setting/panel/SetupMember.tsx
  src/app/teams/[id]/setting/panel/TeamJobAdd.tsx
Labels: enhancement

#493 [S-SC] 쇼케이스 작성 폼 간소화
  src/app/showcase/edit/page.tsx
  src/app/showcase/edit/panel/ShowcaseEditor.style.ts
  src/app/showcase/edit/panel/ShowcaseEditor.tsx
  src/app/showcase/edit/panel/SkillInput.style.ts
  src/app/showcase/edit/panel/formPanel/FormUIEditor.tsx
  src/app/showcase/edit/panel/formPanel/ImageInput.tsx
  src/app/showcase/edit/panel/formPanel/LinkForm.tsx
  src/app/showcase/edit/panel/formPanel/SkillInput.tsx
  src/app/showcase/edit/panel/formPanel/StartEndDateViewer.tsx
  src/app/showcase/edit/panel/formPanel/TeamMembers.tsx
  src/app/showcase/edit/panel/formPanel/TeamName.tsx
  src/app/showcase/panel/icons.tsx
  src/hook/useLinks.tsx
  src/states/useShowCaseState.tsx
  src/types/IShowcaseEdit.ts
Labels: enhancement

#501 [ABOUT] about 페이지 뷰 완성
  src/app/about/@contact/page.tsx
  src/app/about/@dictionary/page.tsx
  src/app/about/@mind/page.tsx
  src/app/about/@notice/page.tsx
  src/app/about/@peer/page.tsx
  src/app/about/@personal/page.tsx
  src/app/about/@service/page.tsx
  src/app/about/layout.tsx
Labels: new feature

#505 [PUBLIC, S-SC] LinkForm에 정규식 로직 추가 및 공용 CuCircularProgress 컴포넌트 추가
  package-lock.json
  src/app/showcase/edit/page.tsx
  src/app/showcase/edit/panel/ShowcaseEditor.tsx
  src/app/showcase/edit/panel/formPanel/ImageInput.tsx
  src/app/showcase/edit/panel/formPanel/LinkForm.tsx
  src/app/showcase/edit/panel/formPanel/SkillInput.style.ts
  src/app/showcase/edit/panel/formPanel/SkillInput.tsx
  src/app/showcase/edit/panel/formPanel/StartEndDateViewer.tsx
  src/app/showcase/edit/panel/formPanel/TeamMembers.tsx
  src/app/showcase/edit/panel/formPanel/TeamName.tsx
  src/components/CuCircularProgress.tsx
  src/hook/useLinks.tsx
Labels: enhancement

#470 [C-MYPAGE] 관심리스트 디자인 적용 및 다크모드 버그 픽스
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/my-page/interests/interests.style.ts
  src/app/my-page/interests/page.tsx
  src/app/my-page/interests/panel/InterestsContents.tsx
  src/app/my-page/layout.style.ts
  src/app/my-page/layout.tsx
  src/app/my-page/panel/NavBar.style.ts
  src/app/my-page/panel/NavBar.tsx
  src/app/my-page/panel/my-page.style.ts
  src/constant/centerdPosition.style.ts
  src/states/useDarkMode.ts
Labels: bug, Design

#508 [H-HITCH] 히치하이킹 디자인 작업 및 백엔드 API 연결
  src/app/hitchhiking/page.tsx
  src/app/hitchhiking/panel/CardContainer.style.ts
  src/app/hitchhiking/panel/CardContainer.tsx
  src/app/hitchhiking/panel/CardStack.tsx
  src/app/hitchhiking/panel/HitchhikingCard.style.ts
  src/app/hitchhiking/panel/HitchhikingCard.tsx
  src/app/hitchhiking/panel/Members.tsx
  src/app/hitchhiking/panel/PostCard.style.ts
  src/app/hitchhiking/panel/PostCard.tsx
  src/types/IPostCard.ts
Labels: link API, Design

#514 [S-SC] 쇼케이스 변경된 화면 작업
  next.config.js
  src/app/showcase/layout.tsx
  src/app/showcase/page.tsx
  src/app/showcase/panel/CardContainer.style.ts
  src/app/showcase/panel/CardContainer.tsx
  src/app/showcase/panel/CardStack.tsx
  src/app/showcase/panel/Interest.tsx
  src/app/showcase/panel/Members.tsx
  src/app/showcase/panel/PhoneFrame.tsx
  src/app/showcase/panel/PostCard.style.ts
  src/app/showcase/panel/PostCard.tsx
  src/app/showcase/panel/ShowcaseCard.style.ts
  src/app/showcase/panel/ShowcaseCard.tsx
  src/app/showcase/panel/ShowcaseHeader.tsx
  src/app/showcase/panel/SkillTag.tsx
  src/app/showcase/showcase.style.ts
  src/types/IPostCard.ts
Labels: enhancement

#506 [PUBLIC] Dropdown 메뉴 재사용성 증가
  package-lock.json
  package.json
  src/app/hitchhiking/panel/HitchhikingCard.tsx
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
  src/components/DropdownMenu.style.ts
  src/components/DropdownMenu.tsx
  src/components/dropdownMenu/IconMenuItem.tsx
  src/components/dropdownMenu/ReportMenuItem.tsx
  src/components/dropdownMenu/ShareMenuItem.tsx
  src/components/dropdownMenu/dropdownMenu.styles.ts
Labels: enhancement

#523 [S-SC] 쇼케이스 리다이렉션 페이지 구현
  src/app/showcase/[id]/panel/ShowcaseViewer.tsx
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/app/teams/[id]/showcase/page.tsx
  src/app/teams/[id]/showcase/panel/ContentSection.tsx
  src/app/teams/[id]/showcase/panel/CreateShowcasePage.tsx
  src/app/teams/[id]/showcase/panel/IntersectionSection.tsx
  src/types/IShowcaseEdit.ts
Labels: enhancement

#535 [C-MYPAGE] 팀리스트에서 승인 대기 표시 추가
  src/app/about/@dictionary/page.tsx
  src/app/team-list/page.tsx
  src/app/team-list/panel/TeamCard.tsx
Labels: enhancement

#539 [HOTFIX] 워크플로우 고장남
  .github/workflows/test.yml
  src/app/panel/MainPage.tsx
Labels: environment

#544 [I-TM] 팀 설정 완료 프로세스
  src/app/panel/main-page/Options.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/InterviewAnswerForm.tsx
  src/app/teams/[id]/setting/panel/RedirectRecruitPage.tsx
  src/app/teams/[id]/setting/panel/SettingSelect.tsx
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/SettingTeamJobs.tsx
  src/app/teams/[id]/setting/panel/SettingTeamMember.tsx
  src/app/teams/[id]/setting/panel/SetupInfo.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamDisperseButton.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamQuitButton.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamActivity.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLocation.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLogo.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamName.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamTime.tsx
Labels: new feature

#548 [S-SC] 쇼케이스 수정폼 에러 수정
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/FormUIEditor.tsx
  src/app/showcase/panel/common/ImageInput.tsx
  src/states/useShowCaseState.tsx
Labels: bug

#536 [PUBLIC] 베타 아이콘 및 카드 추가
  src/app/hitchhiking/panel/CardContainer.tsx
  src/components/BetaBadge.tsx
Labels: enhancement

#549 [S-SC] 팀페이지 내 쇼케이스 작성 API 연동
  src/app/showcase/[id]/page.tsx
  src/app/showcase/edit/page.tsx
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/write/page.tsx
  src/app/teams/[id]/showcase/page.tsx
  src/app/teams/[id]/showcase/panel/ContentSection.tsx
  src/app/teams/[id]/showcase/panel/CreateShowcasePage.tsx
  src/app/teams/[id]/showcase/panel/IntersectionSection.tsx
Labels: enhancement

#553 [C-MYPAGE] 프로필 링크 수정 시 버그 수정
  src/app/my-page/profile/panel/ProfileLinkEditor.tsx
Labels: bug

#547 [D-TP] 공지사항 위젯
  src/app/teams/[id]/panel/WidgetList.tsx
  src/app/teams/[id]/panel/WidgetsRender.tsx
  src/app/teams/[id]/panel/widgets/BoardWidget/PreviewModal.tsx
  src/app/teams/[id]/panel/widgets/BoardWidget/index.style.ts
  src/app/teams/[id]/panel/widgets/BoardWidget/index.tsx
  src/app/teams/[id]/panel/widgets/TmpNoticeWidget.tsx
  src/components/board/ListPanel.tsx
Labels: new feature

#555 [S-SC] 쇼케이스 디테일 페이지 스타일링
  src/app/showcase/[id]/panel/ShowcaseViewer.tsx
  src/app/showcase/detail/[id]/page.tsx
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.style.ts
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
  src/app/showcase/panel/LabelWithIcon.tsx
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/app/showcase/panel/common/SkillInput.style.ts
  src/app/showcase/panel/common/SkillInput.tsx
  src/app/showcase/panel/common/StartEndDateViewer.style.ts
  src/app/showcase/panel/common/StartEndDateViewer.tsx
  src/app/showcase/panel/common/TeamMembers.tsx
  src/app/showcase/panel/common/TeamName.style.ts
  src/app/showcase/panel/common/TeamName.tsx
  src/app/teams/[id]/showcase/panel/IntersectionSection.tsx
  src/components/ToastUIViewer.tsx
Labels: Design

#563 [S-SC] 쇼케이스 관련 스타일링 수정사항 업데이트
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.style.ts
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
  src/app/showcase/edit/page.tsx
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/ImageInput.tsx
  src/app/showcase/panel/common/LinkForm.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/app/showcase/panel/common/SkillInput.style.ts
  src/app/showcase/panel/common/StartEndDateViewer.style.ts
  src/app/showcase/panel/common/TeamMembers.tsx
  src/app/teams/[id]/showcase/page.tsx
  src/app/teams/[id]/showcase/panel/ContentSection.tsx
  src/app/teams/[id]/showcase/panel/IntersectionSection.style.ts
  src/app/teams/[id]/showcase/panel/IntersectionSection.tsx
  src/components/ImageUploadButton.tsx
  src/components/ToastUIViewer.tsx
Labels: Design

#562 [H-SC] 쇼케이스 메인 페이지 에러 수정 및 쇼케이스 버튼 색상 버그 수정
  src/app/panel/main-page/MainShowcase.tsx
  src/app/showcase/page.tsx
  src/app/showcase/panel/PostCard.tsx
  src/app/showcase/panel/ShowcasePc/ShowcasePcView.tsx
Labels: bug

#567 [D-TP] 캘린더 위젯 일정 등록 모달, api 연결
  package-lock.json
  package.json
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarModal.style.ts
  src/app/teams/[id]/panel/widgets/CalenderWidget/CalendarModal.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/EditModalContent.style.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/EditModalContent.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/PreviewModal.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/PreviewModalContent.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/index.tsx
  src/components/CuCheckBox.tsx
  src/components/CuModal.tsx
  src/components/CuTextModal.tsx
  src/icons/CheckBoxEmpty.tsx
  src/icons/CheckBoxSelected.tsx
  src/icons/index.ts
  src/types/ModalTypes.ts
  src/types/WidgetDataTypes.ts
Labels: enhancement, link API

#561 [I-TM] 팀 리스트에서 승인 이후 역할이 보이게끔
  src/app/team-list/panel/TeamCard.tsx
  src/app/teams/[id]/setting/panel/Icons.tsx
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamActivity.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLocation.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLogo.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamName.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamTime.tsx
Labels: enhancement

#572 [HOTFIX] 완료가 안되는 버그
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx
Labels: bug

#574 refactor : Add error respnose messages
  src/app/showcase/detail/[id]/page.tsx
  src/app/showcase/panel/common/TeamName.tsx
  src/app/showcase/write/page.tsx
Labels: bug

#582 [PUBLIC] 베타 뱃지 재수정 및 추가
  public/images/banners/default-banner-1.png
  public/images/banners/default-banner-2.png
  public/images/banners/default-banner-3.png
  public/images/dolphin_spin.gif
  public/images/sad_dolphin.svg
  src/app/hitchhiking/panel/CardContainer.tsx
  src/app/panel/layout-panel/PcNav.tsx
  src/app/panel/main-page/MainCarousel.tsx
  src/app/panel/main-page/MainShowcase.tsx
  src/app/panel/main-page/SearchOption.tsx
  src/app/showcase/panel/PhoneFrame.tsx
  src/app/showcase/panel/ShowcasePc/ShowcasePcView.tsx
  src/app/team-list/page.tsx
  src/app/team-list/panel/TeamsList.tsx
  src/components/Loading.tsx
  src/components/NoDataDolphin.tsx
Labels: bug, enhancement
