Repository peer-42seoul/Peer-Frontend, pull requests merged in 2024-03, with the labels that each got.

#1068 [1.0.6 / D-TP] 팀 페이지 게시판 댓글 버그 수정
  src/components/board/CommentForm.tsx
  src/components/board/CommentList.tsx
  src/components/board/CommentPanel.tsx
Labels: bug

#1085 [1.0.6] PWA 배너 유저 피드백 반영
  next.config.js
  src/app/panel/PwaInstallBanner.tsx
Labels: Design, user feedback

#1086 [1.0.6] ABOUT 페이지의 Contact us의 max length가 적다는 피드백
  src/app/about/@contact/page.tsx
Labels: bug

#1072 [1.0.6 / D-TP] 댓글 일자 표시 버그 수정
  src/components/board/CommentList.tsx
  src/components/board/CommentPanel.tsx
  src/components/board/DetailPanel.tsx
  src/types/TeamBoardTypes.ts
  src/utils/UTCtoLocalTime.ts
Labels: bug

#1096 [1.0.7 / SEO] 메타 데이터 추가
  public/images/og-image.png
  src/app/layout.tsx
Labels: enhancement

#1099 [1.0.7 / DESIGN] 폰트 크기 조정
  src/app/recruit/[id]/panel/RecruitContentText.tsx
  src/app/showcase/detail/[id]/panel/CommentContainer.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/app/showcase/panel/common/StartEndDateViewer.tsx
  src/app/showcase/panel/common/TeamMembers.tsx
  src/components/LabelWithIcon.tsx
  src/components/board/CommentPanel.tsx
  src/components/board/DetailPanel.tsx
  styles/global.css
Labels: enhancement

#1112 [1.0.7/FOOTER] 메인 하단 FOOTER 컴포넌트 생성
  public/icons/public/messageIcon.svg
  src/app/panel/MainLayout.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/main-page/Footer.style.ts
  src/app/panel/main-page/Footer.tsx
  src/app/recruit/[id]/panel/LinkButton.tsx
Labels: Design

#1097 [1.0.7 / D-TP] 게시물 로딩 메시지 오류 수정
  src/app/teams/[id]/board/@detail/page.tsx
  src/app/teams/[id]/board/@list/panel/BoardPostList.tsx
  src/app/teams/[id]/notice/@detail/page.tsx
Labels: bug

#1106 [1.0.7 / DESIGN] 폰트 크기 조정 2
  src/app/recruit/[id]/panel/RecruitContentText.tsx
  src/app/showcase/detail/[id]/panel/CommentContainer.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/app/showcase/panel/common/StartEndDateViewer.tsx
  src/app/showcase/panel/common/TeamMembers.tsx
  src/components/LabelWithIcon.tsx
  src/components/board/CommentPanel.tsx
  src/components/board/DetailPanel.tsx
  styles/global.css
Labels: Design

#1103 [1.0.7 / I-TM] 팀페이지의 메인화면에서 팀원의 리스트를 보여주는 기능 추가
  src/app/teams/[id]/panel/TeamInfoContainer.tsx
  src/app/teams/[id]/panel/TeamMemberList.tsx
Labels: enhancement
