Repository peer-42seoul/Peer-Frontend, pull requests merged in 2024-02, with the labels that each got.

#592 [C-SIGN, C-MYPAGE] 로그인 및 비밀번호 변경 모달 에러 처리
  src/app/login/page.tsx
  src/app/my-page/layout.style.ts
  src/app/my-page/privacy/panel/PasswordChangeModal.tsx
  src/components/EncryptedSender.tsx
Labels: bug

#598 [S-SC] 쇼케이스 내 댓글 기능
  src/app/showcase/detail/[id]/page.tsx
  src/app/showcase/detail/[id]/panel/CommentContainer.tsx
  src/app/showcase/detail/[id]/panel/CommentWriter.tsx
  src/types/IComment.ts
Labels: enhancement

#581 [I-TM] 팀 설정 에러 수정
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamDisperseButton.tsx
  src/app/teams/[id]/setting/panel/TeamEndProcess/TeamQuitButton.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx
Labels: bug

#603 [S-SC] 쇼케이스 내 댓글 기능 스타일 파일 추가
  src/app/showcase/detail/[id]/panel/CommentContainer.style.ts
  src/app/showcase/detail/[id]/panel/CommentContainer.tsx
  src/app/showcase/detail/[id]/panel/CommentWriter.style.ts
  src/app/showcase/detail/[id]/panel/CommentWriter.tsx
Labels: Design

#602 [PUBLIC] socket 전용 환경변수 추가
  src/app/panel/MainPage.tsx
Labels: bug

#622 [D-TP] 팀 게시판 api 연결
  src/app/teams/[id]/board/@detail/page.tsx
  src/app/teams/[id]/board/@edit/page.tsx
  src/app/teams/[id]/board/@edit/panel/PostEditButton.tsx
  src/app/teams/[id]/board/@edit/panel/PostEditForm.tsx
  src/app/teams/[id]/board/@list/page.tsx
  src/app/teams/[id]/board/@list/panel/BoardPostList.tsx
  src/app/teams/[id]/notice/@detail/page.tsx
  src/app/teams/[id]/notice/@detail/panel/CommentList.tsx
  src/app/teams/[id]/notice/@edit/page.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditForm.tsx
  src/app/teams/[id]/notice/@list/panel/NoticeList.tsx
  src/app/teams/[id]/panel/widgets/BoardWidget/PreviewModal.tsx
  src/app/teams/[id]/panel/widgets/BoardWidget/index.tsx
  src/components/board/CommentForm.tsx
  src/components/board/CommentList.tsx
  src/components/board/CommentPanel.tsx
  src/components/board/EditPanel.tsx
  src/components/board/ListPanel.tsx
  src/types/TeamBoardTypes.ts
Labels: bug, link API

#607 [PUBLIC] 토스트 에디터 뷰어 폰트 컬러 변경
  src/components/ToastUIViewer.tsx
  styles/global.css
Labels: bug

#632 [D-TP] 팀 게시판 버그 수정
  src/app/teams/[id]/board/@detail/page.tsx
  src/app/teams/[id]/board/@edit/page.tsx
  src/app/teams/[id]/board/@edit/panel/PostEditButton.tsx
  src/app/teams/[id]/board/@edit/panel/PostEditForm.tsx
  src/app/teams/[id]/board/@setting/page.tsx
  src/app/teams/[id]/board/@setting/panel/BoardItem.tsx
  src/app/teams/[id]/notice/@detail/page.tsx
  src/app/teams/[id]/notice/@edit/page.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditButton.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditForm.tsx
  src/components/DynamicToastEditor.tsx
  src/components/ToastUIEditor.tsx
  src/components/board/EditPanel.style.ts
  src/components/board/EditPanel.tsx
  src/states/useEditorState.ts
  src/types/TeamBoardTypes.ts
  src/types/ToastUI/editor.d.ts
Labels: bug

#625 [PUBLIC] 베타 뱃지 재조정
  public/images/banners/about-mobile.svg
  public/images/banners/about-pc.svg
  public/images/banners/default-mobile.svg
  public/images/banners/default-pc.svg
  src/app/panel/MainPage.tsx
  src/app/panel/layout-panel/PcNav.tsx
  src/app/panel/main-page/MainBanner.tsx
  src/app/panel/main-page/MainCarousel.tsx
  src/app/search/panel/SearchBody.tsx
  src/app/search/panel/SearchHistory.tsx
Labels: enhancement

#645 [D-TP] 팀 페이지 접근 제한 로직 추가
  src/app/teams/[id]/notice/@list/panel/NoticeList.tsx
  src/app/teams/[id]/panel/TeamInfoContainer.tsx
  src/app/teams/[id]/setting/page.tsx
  src/components/board/ListPanel.tsx
Labels: bug

#649 [PUBLIC] 튜토리얼 추가
  public/images/tutorial/interview-type.svg
  src/app/layout.tsx
  src/app/panel/MainPage.tsx
  src/app/recruit/[id]/edit/page.tsx
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
  src/app/recruit/write/page.tsx
  src/app/teams/[id]/board/@list/page.tsx
  src/app/teams/[id]/notice/@list/page.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/AddNewJob.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/SettingTeamJobs.tsx
  src/app/teams/[id]/setting/panel/SettingTeamMember.tsx
  src/components/tutorialContent/MainPageTutorial.tsx
  src/components/tutorialContent/RecruitEditPageTutorial.tsx
  src/components/tutorialContent/RecruitInterviewTutorial.tsx
  src/components/tutorialContent/RecruitPageTutorial.tsx
  src/components/tutorialContent/TeamAnnounceTutorial.tsx
  src/components/tutorialContent/TeamApplicantTutorial.tsx
  src/components/tutorialContent/TeamBoardTutorial.tsx
  src/components/tutorialContent/TeamEndingTutorial.tsx
  src/components/tutorialContent/TeamJobsTutorial.tsx
  src/components/tutorialContent/TeamMemberTutorial.tsx
  src/components/tutorialContent/TeamStatusTutorial.tsx
Labels: new feature

#657 fix: notification check delete
  src/app/panel/PushAlertBanner.tsx
Labels: bug

#658 [C-MYPAGE] 쪽지 페이지 디자인 버그 수정
  src/app/my-page/message/@detail/page.tsx
  src/app/my-page/message/@detail/panel/MessageForm.tsx
  src/app/my-page/message/@list/page.tsx
  src/app/my-page/message/@list/panel/MessageBar.style.ts
  src/app/my-page/message/@list/panel/MessageBar.tsx
  src/app/my-page/message/@list/panel/MessageContainer.tsx
  src/app/my-page/message/@list/panel/MobileMessageItem.tsx
  src/app/my-page/message/@list/panel/NewMessageForm.tsx
  src/app/my-page/message/@list/panel/NewMessageModal.style.ts
  src/app/my-page/message/@list/panel/NewMessageModal.tsx
  src/hook/useInfiniteScroll.tsx
  src/types/TeamBoardTypes.ts
Labels: bug

#669 [PUBLIC] 팀 게시판 튜토리얼 버튼 위치 변경
  src/app/teams/[id]/board/@list/page.tsx
  src/components/board/ListPanel.tsx
Labels: bug

#696 [HOTFIX] 링크 모음, 링크 버튼, 쇼케이스 댓글 문제 해결
  src/app/recruit/[id]/panel/LinkButton.tsx
  src/app/showcase/detail/[id]/page.tsx
  src/app/showcase/detail/[id]/panel/CommentContainer.style.ts
  src/app/showcase/detail/[id]/panel/CommentWriter.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
Labels: bug

#705 [BUG/C-SRC] 다른 페이지에서 검색 안되는 버그 수정
  src/app/search/panel/SearchBody.tsx
Labels: bug

#714 [BUG / PWA] 배너 보이는 방법 로직 교체
  src/app/panel/PushAlertBanner.tsx
  src/app/panel/PwaInstallBanner.tsx
Labels: enhancement

#694 [HOTFIX] 팀 정보 컴포넌트 디자인 추가
  src/app/panel/MuiThemeProvider.tsx
  src/app/teams/[id]/page.tsx
  src/app/teams/[id]/panel/TeamInfoComponent.tsx
  src/app/teams/[id]/panel/TeamInfoContainer.style.ts
  src/app/teams/[id]/panel/TeamInfoContainer.tsx
  src/icons/AccoutBox.tsx
  src/icons/GroupIcon.tsx
  src/icons/TimeIcon.tsx
  src/icons/index.ts
Labels: bug, Design

#706 Style: 피어로그 button disabled, beta badge 추가
  src/app/teams/[id]/panel/NavBar.tsx
  src/components/CuNavBar.style.ts
  src/components/CuNavBar.tsx
Labels: bug

#698 [C-MYPAGE] 닉네임 중복확인 안되는 버그 및 링크 수정 안되는 버그 수정
  src/app/my-page/profile/panel/Profile.style.ts
  src/app/my-page/profile/panel/ProfileBioEditor.tsx
  src/app/my-page/profile/panel/ProfileLinkEditor.tsx
  src/app/my-page/profile/panel/ProfileLinksSection.tsx
  src/types/IUserProfile.ts
Labels: bug

#716 [BUG/ABOUT] ContactUs와 레이아웃
  src/app/about/@contact/page.tsx
  src/app/about/@dictionary/page.tsx
  src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx
  src/components/tutorialContent/TeamStatusTutorial.tsx
Labels: bug

#724 [HOTFIX] 팀 게시판 관리 페이지 버그 픽스 + 쪽지 검색 안내문구 수정
  src/app/my-page/message/@list/panel/NewMessageModal.tsx
  src/app/teams/[id]/board/@list/page.tsx
  src/app/teams/[id]/board/@setting/page.tsx
  src/app/teams/[id]/board/@setting/panel/BoardItem.tsx
Labels: bug

#727 [HOTFIX] 배너 로직 수정
  src/app/about/@peer/page.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/main-page/MainBanner.tsx
  src/app/panel/main-page/MainCarousel.tsx
Labels: enhancement

#746 [HOTFIX] 팀페이지 쇼케이스 페이지 탭 메뉴 오류 수정
  src/app/teams/[id]/panel/NavBar.tsx
Labels: bug

#752 [HOTFIX] 팀 게시판 댓글 글자수 에러 처리 누락
  src/components/board/CommentPanel.tsx
Labels: bug

#763 [HOTFIX] 쪽지와 팀 게시판 디자인 수정
  src/app/my-page/message/@detail/panel/MessageContainer.style.ts
  src/components/board/ListPanel.style.ts
  src/components/board/ListPanel.tsx
Labels: bug, Design

#777 [BUG] 쇼케이스 수정 폼 링크모음
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/LinkForm.tsx
  src/app/showcase/panel/common/LinksViewer.tsx
  src/hook/useLinks.tsx
  src/types/IShowcaseEdit.ts
Labels: bug

#779 [HOTFIX] 팀 페이지 관련 버그 핫픽스
  src/app/teams/[id]/board/@setting/page.tsx
  src/app/teams/[id]/board/@setting/panel/BoardItem.tsx
  src/app/teams/[id]/notice/@edit/panel/NoticeEditForm.tsx
  src/app/teams/[id]/notice/@list/panel/NoticeList.tsx
  src/app/teams/[id]/panel/TeamInfoContainer.tsx
  src/app/teams/[id]/setting/page.tsx
Labels: bug

#794 [BUG] 쇼케이스 메인 페이지 복사 버튼 수정
  src/app/showcase/panel/ShowcaseCard.tsx
Labels: bug

#806 [C-MYPAGE] 쪽지 버튼 로딩 상태 추가
  src/app/my-page/message/@detail/page.tsx
  src/app/my-page/message/@detail/panel/MessageForm.tsx
  src/app/my-page/message/@detail/panel/MessageFormModal.tsx
  src/app/my-page/message/@detail/panel/MobileSendButton.tsx
  src/app/my-page/message/@list/panel/NewMessageForm.tsx
Labels: bug

#809 [HOTFIX] 쇼케이스 작성 페이로드 수정
  src/app/showcase/panel/ShowcaseEditor.tsx
Labels: bug

#865 [PUBLIC] SkillAutocomplete 컴포넌트에서 간헐적으로 선택한 태그가 사라지는 현상 수정
  src/components/SkillAutocomplete.tsx
Labels: bug

#861 [S-SC] 쇼케이스 디자인 수정
  src/app/showcase/panel/ShowcaseEditor.tsx
  src/app/showcase/panel/common/ImageInput.tsx
  src/app/showcase/write/page.tsx
Labels: Design

#878 [1.0.2 / D-TP] 팀 리스트로 돌아가기 버튼 크기 조정
  src/app/teams/[id]/page.tsx
Labels: bug, Design

#892 [BUG] 모집완료 시 지원하기 버튼 막기
  src/app/recruit/[id]/panel/ApplyFormButton.tsx
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
Labels: bug

#894 [BUG] 토스트 뷰어 다크모드 에러
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
  src/components/ToastUIViewer.tsx
Labels: bug

#899 [PUBLIC] NextImage 반응형 공용 컴포넌트 추가
  src/app/showcase/detail/[id]/panel/CommentContainer.tsx
  src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
  src/components/CuPhotoBox.tsx
  src/types/IComment.ts
Labels: enhancement

#919 [1.0.3 / D-TP] 팀 페이지 사이드바 없는 레이아웃 디자인 수정
  src/app/teams/[id]/board/layout.tsx
  src/app/teams/[id]/layout.style.ts
  src/app/teams/[id]/layout.tsx
  src/app/teams/[id]/notice/layout.tsx
Labels: bug, Design

#929 [1.0.3 / J-TB] 모집글 삭제 기능 추가
  src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
  src/components/dropdownMenu/dropdownMenu.styles.ts
Labels: new feature, link API

#924 [1.0.3 / ABOUT] 가시성 롤백 및 텍스트 필드 스타일 변경
  src/app/about/@announce/page.tsx
  src/app/about/@contact/page.tsx
  src/app/about/layout.tsx
  src/app/panel/MuiThemeProvider.tsx
Labels: enhancement, Design

#933 [HOTFIX] 쇼케이스와 히치하이킹이 안보이는 현상
  src/app/panel/MainLayout.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/layout-panel/AlertIcon.tsx
  src/app/teams/[id]/layout.tsx
  src/app/teams/[id]/page.tsx
Labels: HOTFIX

#940 [HOTFIX] Next Image 경고 수정
  src/app/panel/main-page/MainBanner.tsx
  src/app/panel/main-page/MainShowcase.tsx
  src/components/CuPhotoBox.tsx
Labels: bug

#948 [C-MAIN][J-TB][C-TB] 각종 디자인 수정, 에러 수정
  src/app/panel/MainPage.tsx
  src/app/panel/layout-panel/Header.tsx
  src/app/panel/layout-panel/MobileNav.tsx
  src/app/panel/layout-panel/Nav.style.ts
  src/app/panel/layout-panel/PcNav.tsx
  src/app/panel/main-page/SearchButton.tsx
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
  src/app/recruit/[id]/panel/RecruitInfo.tsx
  src/app/recruit/[id]/panel/RecruitInfoElement.tsx
  src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
  src/app/search/panel/SearchBody.tsx
  src/components/dropdownMenu/IconMenuItem.tsx
Labels: enhancement, Design

#951 [1.0.3 / C-MYPAGE] 모바일 쪽지 삭제 버그 수정
  src/app/my-page/message/@list/panel/MobileMessageItem.style.ts
  src/app/my-page/message/@list/panel/MobileMessageItem.tsx
Labels: bug, Design

#956 [1.0.3 / J-TB] 모집글 삭제 기능 보완
  src/app/recruit/[id]/page.tsx
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
  src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
Labels: new feature

#955 [1.0.3 / D-TP] 팀 페이지 사이드바 디자인 보완
  src/app/teams/[id]/panel/NavBar.tsx
  src/components/CuNavBar.style.ts
  src/components/CuNavBar.tsx
  src/components/NavBarBox.style.ts
  src/hook/useMedia.tsx
Labels: Design

#957 [1.0.3 / PUBLIC] 튜토리얼 모달 개선
  src/app/recruit/[id]/panel/RecruitDetailPage.tsx
  src/app/teams/[id]/board/@list/page.tsx
  src/app/teams/[id]/notice/@list/page.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
  src/app/teams/[id]/setting/panel/SettingTeamJobs.tsx
  src/components/Tutorial.tsx
  src/components/tutorialContent/MainPageTutorial.tsx
  src/components/tutorialContent/RecruitEditPageTutorial.tsx
  src/components/tutorialContent/SkillsTutorial.tsx
  src/components/tutorialContent/TeamAnnounceTutorial.tsx
  src/components/tutorialContent/TeamApplicantTutorial.tsx
  src/components/tutorialContent/TeamBoardTutorial.tsx
  src/components/tutorialContent/TeamEndingTutorial.tsx
  src/components/tutorialContent/TeamJobsTutorial.tsx
  src/components/tutorialContent/TeamMemberTutorial.tsx
  src/components/tutorialContent/TeamStatusTutorial.tsx
Labels: Design

#923 [1.0.3 / I-TM] 새로고침을 이용한 로직을 다른 로직으로 바꾸는 작업
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/setting/panel/ApplicantList.tsx
  src/app/teams/[id]/setting/panel/SettingTeamMember.tsx
Labels: enhancement

#950 [1.0.3 / C-ALARM] 알림 기능 추가
  next.config.js
  package-lock.json
  package.json
  public/worker/index.js
  src/app/panel/MainPage.tsx
  src/app/panel/PushAlertBanner.tsx
  src/app/panel/PwaInstallBanner.tsx
  src/app/panel/layout-panel/AlertIcon.tsx
  src/app/panel/layout-panel/alert-panel/AlertCard.tsx
  src/app/teams/[id]/setting/page.tsx
  src/states/useAlarmStorage.ts
  src/states/useAuthStore.tsx
  src/states/useSocket.tsx
Labels: new feature

#988 [1.0.3 / C-MYPAGE] 쪽지 상세페이지 말풍선 줄바꿈 버그
  src/app/my-page/message/@detail/panel/MessageItem.tsx
Labels: bug, Design

#1015 Release 1.0.4
  public/icons/icons.json
  public/manifest.json
  src/api/fetchers.ts
  src/app/admin/announce/Announce.tsx
  src/app/my-page/interests/page.tsx
  src/app/panel/MainPage.tsx
  src/app/panel/PushAlertBanner.tsx
  src/app/panel/layout-panel/AlertIcon.tsx
  src/app/teams/[id]/panel/widgets/CalenderWidget/EditModalContent.tsx
  src/app/teams/[id]/setting/page.tsx
  src/app/teams/[id]/showcase/page.tsx
  src/components/CuAvatar.tsx
  src/components/CuPhotoBox.tsx
  src/components/ToastUIEditor.tsx
  src/components/ToastUIEditorAdmin.tsx
  src/components/dropdownMenu/ShareMenuItem.tsx
  src/states/useAuthStore.tsx
Labels: Release
